repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--config-file=mypy.ini]
        additional_dependencies: [pydantic==2.5.3, httpx, click, pytest]

  -   repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
      -   id: isort